[package]
name = "fay"
description = "Will be added later"
version = "0.1.1"
edition = "2021"
license = "MIT"
homepage = "https://github.com/p32929/fay_cli"
readme = "README.md"
keywords = [
    "windows",
    "linux",
    "shell",
    "bash",
    "rust",
    "cli",
    "mac",
    "automation",
    "awesome",
    "cross-platform",
    "simple",
    "crates",
    "automate",
    "cmd",
    "intuitive",
    "p32929",
    "fay",
    "run-saved-commands",
    "shell-automation",
]
categories = [
    "windows",
    "linux",
    "shell",
    "bash",
    "rust",
    "cli",
    "mac",
    "automation",
    "awesome",
    "cross-platform",
    "simple",
    "crates",
    "automate",
    "cmd",
    "intuitive",
    "p32929",
    "fay",
    "run-saved-commands",
    "shell-automation",
]
exclude = [".vscode/*"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
